# Generated by Django 4.1.5 on 2023-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('login_at', models.DateTimeField()),
            ],
        ),
    ]
